### ISSUE TITLE
Failed to install on vagrant 1.0.4 /Ubuntu 12.04

### ISSUE THREAD

**Issue by number5** [mitchellh/vagrant-rake#3]
I'm trying to install via `vagrant gem install vagrant-rake`

got error while building extension for ffi-0.6.3

> Fetching: erubis-2.6.6.gem (100%)
> Fetching: json-1.4.6.gem (100%)
> Building native extensions.  This could take a while...
> Fetching: net-ssh-2.0.24.gem (100%)
> Fetching: i18n-0.4.2.gem (100%)
> Building native extensions.  This could take a while...
> ERROR:  Error installing vagrant-rake:
> ERROR: Failed to build gem native extension.
> 
> /opt/vagrant/embedded/bin/ruby extconf.rb
> extconf.rb:6: Use RbConfig instead of obsolete and deprecated Config.
> checking for ffi.h in /usr/local/include... no
> checking for rb_thread_blocking_region()... yes
> creating extconf.h
> creating Makefile
> 
> make
> Configuring libffi
> cd /home/bruce/.vagrant.d/gems/gems/ffi-0.6.3/ext/ffi_c/libffi && make
> make[1]: Entering directory `/home/bruce/.vagrant.d/gems/gems/ffi-0.6.3/ext/ffi_c/libffi'
> make "AR_FLAGS=" "CC_FOR_BUILD=" "CFLAGS=" "CXXFLAGS=" "CFLAGS_FOR_BUILD=" "CFLAGS_FOR_TARGET=" "INSTALL=/usr/bin/install -c" "INSTALL_DATA=/usr/bin/install -c -m 644" "INSTALL_PROGRAM=/usr/bin/install -c" "INSTALL_SCRIPT=/usr/bin/install -c" "JC1FLAGS=" "LDFLAGS=-I/opt/vagrant/bin/../embedded/include -L/opt/vagrant/bin/../embedded/lib}" "LIBCFLAGS=" "LIBCFLAGS_FOR_TARGET=" "MAKE=make" "MAKEINFO=/bin/bash /home/bruce/.vagrant.d/gems/gems/ffi-0.6.3/ext/ffi_c/libffi/missing --run makeinfo " "PICFLAG=" "PICFLAG_FOR_TARGET=" "RUNTESTFLAGS=" "SHELL=/bin/bash" "exec_prefix=/usr/local" "infodir=/usr/local/share/info" "libdir=/usr/local/lib" "prefix=/usr/local" "AR=ar" "AS=as" "CC=gcc" "CXX=g++" "LD=/usr/bin/ld -m elf_x86_64" "NM=/usr/bin/nm -B" "RANLIB=ranlib" "DESTDIR=" all-recursive
> make[2]: Entering directory`/home/bruce/.vagrant.d/gems/gems/ffi-0.6.3/ext/ffi_c/libffi'
> Making all in include
> make[3]: Entering directory `/home/bruce/.vagrant.d/gems/gems/ffi-0.6.3/ext/ffi_c/libffi/include'
> make[3]: Nothing to be done for`all'.
> make[3]: Leaving directory `/home/bruce/.vagrant.d/gems/gems/ffi-0.6.3/ext/ffi_c/libffi/include'
> Making all in testsuite
> make[3]: Entering directory`/home/bruce/.vagrant.d/gems/gems/ffi-0.6.3/ext/ffi_c/libffi/testsuite'
> make[3]: Nothing to be done for `all'.
> make[3]: Leaving directory`/home/bruce/.vagrant.d/gems/gems/ffi-0.6.3/ext/ffi_c/libffi/testsuite'
> Making all in man
> make[3]: Entering directory `/home/bruce/.vagrant.d/gems/gems/ffi-0.6.3/ext/ffi_c/libffi/man'
> make[3]: Nothing to be done for`all'.
> make[3]: Leaving directory `/home/bruce/.vagrant.d/gems/gems/ffi-0.6.3/ext/ffi_c/libffi/man'
> make[3]: Entering directory`/home/bruce/.vagrant.d/gems/gems/ffi-0.6.3/ext/ffi_c/libffi'
> /bin/bash ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I. -I./include -Iinclude -I./src  -Wall -g -fexceptions  -c -o src/debug.lo src/debug.c
> libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -Wall -g -fexceptions -c src/debug.c  -fPIC -DPIC -o src/.libs/debug.o
> /bin/bash ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I. -I./include -Iinclude -I./src  -Wall -g -fexceptions  -c -o src/prep_cif.lo src/prep_cif.c
> libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -Wall -g -fexceptions -c src/prep_cif.c  -fPIC -DPIC -o src/.libs/prep_cif.o
> /bin/bash ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I. -I./include -Iinclude -I./src  -Wall -g -fexceptions  -c -o src/types.lo src/types.c
> libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -Wall -g -fexceptions -c src/types.c  -fPIC -DPIC -o src/.libs/types.o
> /bin/bash ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I. -I./include -Iinclude -I./src  -Wall -g -fexceptions  -c -o src/raw_api.lo src/raw_api.c
> libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -Wall -g -fexceptions -c src/raw_api.c  -fPIC -DPIC -o src/.libs/raw_api.o
> /bin/bash ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I. -I./include -Iinclude -I./src  -Wall -g -fexceptions  -c -o src/java_raw_api.lo src/java_raw_api.c
> libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -Wall -g -fexceptions -c src/java_raw_api.c  -fPIC -DPIC -o src/.libs/java_raw_api.o
> /bin/bash ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I. -I./include -Iinclude -I./src  -Wall -g -fexceptions  -c -o src/closures.lo src/closures.c
> libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -Wall -g -fexceptions -c src/closures.c  -fPIC -DPIC -o src/.libs/closures.o
> /bin/bash ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I. -I./include -Iinclude -I./src  -Wall -g -fexceptions  -c -o src/x86/ffi64.lo src/x86/ffi64.c
> libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -Wall -g -fexceptions -c src/x86/ffi64.c  -fPIC -DPIC -o src/x86/.libs/ffi64.o
> /bin/bash ./libtool   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I. -I./include -Iinclude -I./src  -I. -I./include -Iinclude -I./src  -c -o src/x86/unix64.lo src/x86/unix64.S
> libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -I. -I./include -Iinclude -I./src -c src/x86/unix64.S  -fPIC -DPIC -o src/x86/.libs/unix64.o
> /bin/bash ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I. -I./include -Iinclude -I./src  -Wall -g -fexceptions  -c -o src/x86/ffi.lo src/x86/ffi.c
> libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -Wall -g -fexceptions -c src/x86/ffi.c  -fPIC -DPIC -o src/x86/.libs/ffi.o
> /bin/bash ./libtool   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I. -I./include -Iinclude -I./src  -I. -I./include -Iinclude -I./src  -c -o src/x86/sysv.lo src/x86/sysv.S
> libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -I. -I./include -Iinclude -I./src -c src/x86/sysv.S  -fPIC -DPIC -o src/x86/.libs/sysv.o
> /bin/bash ./libtool --tag=CC   --mode=link gcc -Wall -g -fexceptions  -version-info `grep -v '^#' ./libtool-version`  -I/opt/vagrant/bin/../embedded/include -L/opt/vagrant/bin/../embedded/lib} -o libffi.la -rpath /usr/local/lib src/debug.lo src/prep_cif.lo src/types.lo src/raw_api.lo src/java_raw_api.lo src/closures.lo                     src/x86/ffi64.lo src/x86/unix64.lo src/x86/ffi.lo src/x86/sysv.lo  
> libtool: link: gcc -shared  src/.libs/debug.o src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/x86/.libs/ffi64.o src/x86/.libs/unix64.o src/x86/.libs/ffi.o src/x86/.libs/sysv.o   -L/opt/vagrant/bin/../embedded/lib}    -Wl,-soname -Wl,libffi.so.5 -o .libs/libffi.so.5.0.10
> libtool: link: (cd ".libs" && rm -f "libffi.so.5" && ln -s "libffi.so.5.0.10" "libffi.so.5")
> libtool: link: (cd ".libs" && rm -f "libffi.so" && ln -s "libffi.so.5.0.10" "libffi.so")
> libtool: link: ( cd ".libs" && rm -f "libffi.la" && ln -s "../libffi.la" "libffi.la" )
> /bin/bash ./libtool --tag=CC   --mode=link gcc -Wall -g -fexceptions   -I/opt/vagrant/bin/../embedded/include -L/opt/vagrant/bin/../embedded/lib} -o libffi_convenience.la  src/debug.lo src/prep_cif.lo src/types.lo src/raw_api.lo src/java_raw_api.lo src/closures.lo                     src/x86/ffi64.lo src/x86/unix64.lo src/x86/ffi.lo src/x86/sysv.lo  
> libtool: link: ar cru .libs/libffi_convenience.a src/.libs/debug.o src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/x86/.libs/ffi64.o src/x86/.libs/unix64.o src/x86/.libs/ffi.o src/x86/.libs/sysv.o 
> libtool: link: ranlib .libs/libffi_convenience.a
> libtool: link: ( cd ".libs" && rm -f "libffi_convenience.la" && ln -s "../libffi_convenience.la" "libffi_convenience.la" )
> make[3]: Leaving directory `/home/bruce/.vagrant.d/gems/gems/ffi-0.6.3/ext/ffi_c/libffi'
> make[2]: Leaving directory`/home/bruce/.vagrant.d/gems/gems/ffi-0.6.3/ext/ffi_c/libffi'
> make[1]: Leaving directory `/home/bruce/.vagrant.d/gems/gems/ffi-0.6.3/ext/ffi_c/libffi'
> compiling DynamicLibrary.c
> compiling Variadic.c
> compiling AutoPointer.c
> compiling Platform.c
> compiling Function.c
> compiling Pointer.c
> compiling ArrayType.c
> compiling StructByValue.c
> compiling Struct.c
> Struct.c: In function ‘struct_set_pointer’:
> Struct.c:300:17: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long int’ [-Wformat]
> Struct.c:300:17: warning: format ‘%d’ expects argument of type ‘int’, but argument 5 has type ‘size_t’ [-Wformat]
> compiling Buffer.c
> compiling MemoryPointer.c
> compiling MethodHandle.c
> compiling Call.c
> compiling Types.c
> compiling Type.c
> compiling FunctionInfo.c
> compiling ClosurePool.c
> compiling AbstractMemory.c
> compiling ffi.c
> compiling LastError.c
> compiling StructLayout.c
> StructLayout.c: In function ‘struct_layout_initialize’:
> StructLayout.c:363:9: error: lvalue required as left operand of assignment
> make: **\* [StructLayout.o] Error 1

**Comment by sbfaulkner** [comment]
also failed on OS X... I'll troubleshoot more when I get a chance...

```
Building native extensions.  This could take a while...
ERROR:  Error installing vagrant-rake:
    ERROR: Failed to build gem native extension.

        /Applications/Vagrant/embedded/bin/ruby extconf.rb
checking for ruby/re.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Applications/Vagrant/embedded/bin/ruby
/Applications/Vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:491:in `block in try_compile'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:443:in `with_werror'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:491:in `try_compile'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:931:in `block in have_header'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:790:in `block in checking_for'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:284:in `block (2 levels) in postpone'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:254:in `open'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:284:in `block in postpone'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:254:in `open'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:280:in `postpone'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:789:in `checking_for'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/mkmf.rb:930:in `have_header'
    from extconf.rb:17:in `<main>'


Gem files will remain installed in /Users/brent.faulkner/.vagrant.d/gems/gems/json-1.4.6 for inspection.
Results logged to /Users/brent.faulkner/.vagrant.d/gems/gems/json-1.4.6/ext/json/ext/generator/gem_make.out
```

**Comment by splaspood** [comment]
The two issues mentioned here appear to be unrelated, one being an issue with ffi the other with vagrant-rake it appears.   

In the first case, this appears to be the problem/solution https://github.com/ffi/ffi/pull/208

**Comment by splaspood** [comment]
Excuse me, in the 2nd case the issue appears to be the JSON gem, although still not apparently related to ffi.

**Comment by sheerun** [comment]
I experienced first error...

**Comment by paaloeye** [comment]
@sbfaulkner I had the same problem.
In my case I had fixed it by installation XCode Command Line Tools.
